apiVersion: v1
kind: Secret
metadata:
  name: servicey-url
  namespace: servicex
type: Opaque
data:
  Cleverbit__Url: aHR0cDovL3NlcnZpY2V5LnNlcnZpY2V5LnN2Yy5jbHVzdGVyLmxvY2Fs # Base64 encoded value of http://servicey.servicey.svc.cluster.local
